//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIL_Injector_Decrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSIL_Injector_Decrypt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cibVAGgDRVjMjQs {
            get {
                object obj = ResourceManager.GetObject("cibVAGgDRVjMjQs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 丝维尔吾迪儿伊艾诶勒尺艾马比艾比艾 {
            get {
                object obj = ResourceManager.GetObject("丝维尔吾迪儿伊艾诶勒尺艾马比艾比艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 儿艾弗斯艾艾艾贝尺马哦维 {
            get {
                object obj = ResourceManager.GetObject("儿艾弗斯艾艾艾贝尺马哦维", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 吉尺西开吉德豆斯豆吉艾马弗艾娜尺西儿吾豆吉艾丝 {
            get {
                object obj = ResourceManager.GetObject("吉尺西开吉德豆斯豆吉艾马弗艾娜尺西儿吾豆吉艾丝", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 吉迪吾吾豆西豆比艾屁艾迪吉艾斯 {
            get {
                object obj = ResourceManager.GetObject("吉迪吾吾豆西豆比艾屁艾迪吉艾斯", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 吾艾维斯开德艾迪伊艾 {
            get {
                object obj = ResourceManager.GetObject("吾艾维斯开德艾迪伊艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 哦贝豆马维西吾提吾迪伊西哦艾马艾 {
            get {
                object obj = ResourceManager.GetObject("哦贝豆马维西吾提吾迪伊西哦艾马艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 娜吾艾艾艾艾西吾艾尔贼 {
            get {
                object obj = ResourceManager.GetObject("娜吾艾艾艾艾西吾艾尔贼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 尺伊维诶迪艾伊 {
            get {
                object obj = ResourceManager.GetObject("尺伊维诶迪艾伊", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 屁艾吉尔吾伊马提艾艾儿尔吉娜马屁德贼伊吾吉克吾 {
            get {
                object obj = ResourceManager.GetObject("屁艾吉尔吾伊马提艾艾儿尔吉娜马屁德贼伊吾吉克吾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 弗艾艾勒尔伊尔丝迪艾 {
            get {
                object obj = ResourceManager.GetObject("弗艾艾勒尔伊尔丝迪艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 斯开勒德艾贼艾 {
            get {
                object obj = ResourceManager.GetObject("斯开勒德艾贼艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 杰杰哦屁维弗尺伊 {
            get {
                object obj = ResourceManager.GetObject("杰杰哦屁维弗尺伊", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 杰艾杰伊贼马杰西开弗维比艾 {
            get {
                object obj = ResourceManager.GetObject("杰艾杰伊贼马杰西开弗维比艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 维克娜吾吉提吉勒吾伊克弗娜艾艾 {
            get {
                object obj = ResourceManager.GetObject("维克娜吾吉提吉勒吾伊克弗娜艾艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 艾丝迪豆提艾斯艾艾屁儿吉 {
            get {
                object obj = ResourceManager.GetObject("艾丝迪豆提艾斯艾艾屁儿吉", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 艾吉诶屁西屁哦克 {
            get {
                object obj = ResourceManager.GetObject("艾吉诶屁西屁哦克", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 艾吾屁杰吉艾吾弗尺艾尔比马西迪贼 {
            get {
                object obj = ResourceManager.GetObject("艾吾屁杰吉艾吾弗尺艾尔比马西迪贼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 艾开吾豆西吾艾豆伊勒迪迪艾 {
            get {
                object obj = ResourceManager.GetObject("艾开吾豆西吾艾豆伊勒迪迪艾", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 贝尔比艾吉艾伊 {
            get {
                object obj = ResourceManager.GetObject("贝尔比艾吉艾伊", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 贼吾德贝哦丝艾艾吉开维儿弗吾豆伊诶迪马吾开 {
            get {
                object obj = ResourceManager.GetObject("贼吾德贝哦丝艾艾吉开维儿弗吾豆伊诶迪马吾开", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 贼迪娜迪吾吾马艾贝尺尔哦吾吾屁艾尔比 {
            get {
                object obj = ResourceManager.GetObject("贼迪娜迪吾吾马艾贝尺尔哦吾吾屁艾尔比", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 迪儿伊尺迪伊艾艾比诶吾屁豆比马儿儿 {
            get {
                object obj = ResourceManager.GetObject("迪儿伊尺迪伊艾艾比诶吾屁豆比马儿儿", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
